mbit_Robot.Music_Car(mbit_Robot.enMusic.birthday)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Run, 50)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Green)
basic.pause(2000)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Back, 60)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Red)
basic.pause(2000)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Left, 70)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Cyan)
basic.pause(2000)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Right, 80)
basic.pause(2000)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Pinkish)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Run, 90)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Green)
basic.pause(2000)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Back, 100)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Red)
basic.pause(2000)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Left, 110)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Cyan)
basic.pause(2000)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Right, 120)
basic.pause(2000)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Pinkish)
basic.pause(200)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Left, 120)
basic.pause(500)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Right, 120)
basic.pause(500)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Left, 120)
basic.pause(500)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Right, 120)
basic.pause(500)
mbit_Robot.CarCtrlSpeed(mbit_Robot.CarState.Car_Stop, 120)
basic.pause(500)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Green)
basic.pause(500)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Red)
basic.pause(500)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Cyan)
basic.pause(500)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Pinkish)
basic.pause(500)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.Yellow)
basic.pause(500)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.White)
basic.pause(2000)
mbit_Robot.RGB_Car_Big2(mbit_Robot.enColor.OFF)
